version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily" # "weekly", "monthly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
