name: Node.js CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    needs: code-analysis

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build and Push to Dockerhub
      run: |
        DOCKER_TAG="${{ vars.DOCKER_USERNAME }}/devops-code-and-build:${GITHUB_SHA}"
        echo "${DOCKER_TAG}"
        docker build -t "${DOCKER_TAG}" .
        docker push "${DOCKER_TAG}"